BEGIN;

-- Inserting dummy users data
-- We insert the id manually to be able to create the cards belonging to the users
-- If we do not provide it, it will be randomly generated by gen_random_uuid()
INSERT INTO "user" ("id", "email", "first_name", "last_name", "password", "avatar_url", "address") VALUES
('235c1fb1-5dbe-4cb6-b18e-78b3554c80af', 'chuck.norris@gmail.com', 'Chuck', 'Norris', '$2b$12$JpKk363OUJAJKSmpS4XlGubVFr/EmFjHRtAFx9zldHmks8tuGyYoG', 'chuck.jpg', '1 Parvis de la Défense'),
('d4ddb3ae-e748-44dd-aacb-a3eced9dda85', 'bruce.lee@free.fr', 'bruce', 'lee', '$2b$12$OKLm0NBaYEihah7vOLGjJ.n7kuKxfMC6T09OZKG3nbwm1dZTZKVEm', '/img/default_avatar.png', 'Hong-Kong'),
('7dbcfb4a-639c-401d-b2a8-0f6d5511fece', 'mickey.mouse@disney.fr', 'Mickey', 'Mouse', '$2b$12$1vh.xdxK69qIE013.5Tp2eWbNpgJQJcF.o4R/S5W8UmcJC.i64ywm', 'mickey.jpg', 'Disneyland');

-- Inserting new dummy cards data
INSERT INTO "card" ("id", "title", "category", "index", "enterprise_name", "enterprise_activity", "contract_type", "description", "offer_url", "location", "salary", "job_title", "rating", "color", "is_deleted", "comments", "reminder", "logo_url", "created_at", "user_id") VALUES
('e7d79e8b-4d13-42c1-af67-1f582e84d8a4', 'Carte Google', 'Mes offres', 0, 'Google', 'Technologie', 'CDI', 'Ingénieur logiciel chez Google', 'http://linkedin.com/offre_google', 'Mountain View', '120000€ annuels', 'Ingénieur logiciel', 4, 'green', 'f', 'Excellente opportunité', '2023-08-10 00:00:00+00', 'http://www.google.com/logo.jpg', '2023-08-10 00:00:00+00', '235c1fb1-5dbe-4cb6-b18e-78b3554c80af'),
('3f056207-22a0-4e38-91f4-9a40dd6a4bc2', 'Carte Amazon', 'Mes offres', 1, 'Amazon', 'Commerce électronique', 'CDD', 'Analyste financier chez Amazon', 'http://linkedin.com/offre_amazon', 'Seattle', '90000€ annuels', 'Analyste financier', 3, 'yellow', 'f', 'Bonne opportunité de croissance', '2023-08-12 00:00:00+00', 'http://www.amazon.com/logo.jpg', '2023-08-12 00:00:00+00', '235c1fb1-5dbe-4cb6-b18e-78b3554c80af'),
('29e35264-2f80-412b-9529-ea51d4f91a79', 'Carte Tesla', 'Mes offres', 0, 'Tesla', 'Automobile', 'Stage', 'Stage en ingénierie automobile chez Tesla', 'http://linkedin.com/offre_tesla', 'Palo Alto', '1500€ par mois', 'Ingénieur automobile', 5, 'blue', 'f', 'Opportunité passionnante', '2023-08-08 00:00:00+00', 'http://www.tesla.com/logo.jpg', '2023-08-08 00:00:00+00', '235c1fb1-5dbe-4cb6-b18e-78b3554c80af'),
('92b15507-2d99-4488-b86a-c5016cf02b25', 'Carte Microsoft', 'Mes offres', 0, 'Microsoft', 'Technologie', 'CDI', 'Ingénieur logiciel chez Microsoft', 'http://linkedin.com/offre_microsoft', 'Redmond', '110000€ annuels', 'Ingénieur logiciel', 4, 'green', 'f', 'Belle opportunité chez un géant', '2023-08-15 00:00:00+00', 'http://www.microsoft.com/logo.jpg', '2023-08-15 00:00:00+00', '235c1fb1-5dbe-4cb6-b18e-78b3554c80af'),
('72616da2-9829-40f9-92ec-b8cd64055d12', 'Carte SpaceX', 'Mes offres', 1, 'SpaceX', 'Aérospatiale', 'Stage', 'Stage en ingénierie spatiale chez SpaceX', 'http://linkedin.com/offre_spacex', 'Hawthorne', '1500€ par mois', 'Ingénieur spatial', 5, 'blue', 'f', 'Explorez l''espace avec nous', '2023-08-20 00:00:00+00', 'http://www.spacex.com/logo.jpg', '2023-08-20 00:00:00+00', '235c1fb1-5dbe-4cb6-b18e-78b3554c80af'),
('c3e8d9fc-d535-4c0d-9189-1a5b5de69d0f', 'Carte IBM', 'Mes offres', 0, 'IBM', 'Informatique', 'CDI', 'Ingénieur système chez IBM', 'http://linkedin.com/offre_ibm', 'Armonk', '100000€ annuels', 'Ingénieur système', 3, 'yellow', 'f', 'Solide entreprise informatique', '2023-08-18 00:00:00+00', 'http://www.ibm.com/logo.jpg', '2023-08-18 00:00:00+00', '235c1fb1-5dbe-4cb6-b18e-78b3554c80af');

-- Inserting new dummy contacts data
INSERT INTO "public"."contact" ("id", "first_name", "last_name", "occupation", "email", "phone", "linkedin_profile", "enterprise", "comments", "color", "user_id") VALUES
('3a5c8a22-8a29-4161-81b8-52007808630e', 'Elon', 'Musk', 'Entrepreneur', 'elon.musk@tesla.com', '123456789', 'http://linkedin.com/elon-musk', 'Tesla', 'Visionnaire et innovateur', '#fff', '235c1fb1-5dbe-4cb6-b18e-78b3554c80af'),
('a25b7b11-9b8c-4f8d-9b6e-8daac7a2e7f2', 'Jeff', 'Bezos', 'Entrepreneur', 'jeff.bezos@amazon.com', '987654321', 'http://linkedin.com/jeff-bezos', 'Amazon', 'Fondateur d''Amazon', '#fff', '235c1fb1-5dbe-4cb6-b18e-78b3554c80af'),
('5f7d55c1-75e0-4f66-a7ef-59c736d1e4b2', 'Sundar', 'Pichai', 'CEO', 'sundar.pichai@google.com', '555-1234', 'http://linkedin.com/sundar-pichai', 'Google', 'PDG de Google', '#fff', '235c1fb1-5dbe-4cb6-b18e-78b3554c80af'),
('8e9a49b3-172b-4c94-b547-44a01716f90b', 'Satya', 'Nadella', 'CEO', 'satya.nadella@microsoft.com', '987654321', 'http://linkedin.com/satya-nadella', 'Microsoft', 'Leadership inspirant', '#fff', '235c1fb1-5dbe-4cb6-b18e-78b3554c80af'),
('eb703155-b40d-4e4a-9139-05e2709a3aa7', 'Elon', 'Musk', 'Entrepreneur', 'elon.musk@spacex.com', '123456789', 'http://linkedin.com/elon-musk', 'SpaceX', 'Révolutionnaire de l''espace', '#fff', '235c1fb1-5dbe-4cb6-b18e-78b3554c80af'),
('ac965a49-4163-4b58-9db9-b5f84f4fe1af', 'Ginni', 'Rometty', 'Ex-CEO', 'ginni.rometty@ibm.com', '555-1234', 'http://linkedin.com/ginni-rometty', 'IBM', 'Leadership remarquable chez IBM', '#fff', '235c1fb1-5dbe-4cb6-b18e-78b3554c80af');

COMMIT;
